In [1]:
import pandas as pd

In [ ]:
rs = pd.read_excel("exercicio_prova_tabelas.xlsx")
redes = rs["REDES"].value_counts()
totalRedes = redes.sum()
redesDF = pd.DataFrame(redes.reset_index().values, columns=["Rede Social", "Frequencia Absoluta"])
redesDF["Frequencia Relativa"] = redesDF["Frequencia Absoluta"]/totalRedes
redesDF["FR%"] = redesDF["Frequencia Relativa"]*100
redesDF.loc["Total: "] = redesDF.sum()
redesDF.loc["Total: ", "Rede Social"] = "Total"
redesDF-

        Rede Social Frequencia Absoluta Frequencia Relativa    FR%
0         Instagram                   4                 0.4   40.0
1            TikTok                   3                 0.3   30.0
2           YouTube                   2                 0.2   20.0
3          WhatsApp                   1                 0.1   10.0
Total:        Total                  10                 1.0  100.0

In [6]:
g = pd.read_excel("exercicio_prova_tabelas.xlsx")
genero = g["Genero"].value_counts()
totalG = genero.sum()
generoDF= pd.DataFrame(genero.reset_index().values, columns=["Genero","FA"])
generoDF["FR"] = generoDF["FA"]/totalG
generoDF["FR%"] = generoDF["FR"]*100
generoDF.loc["Total: "]= generoDF.sum()
generoDF.loc["Total: ", "Genero"]="Total"
generoDF

        Genero  FA   FR    FR%
0         Rock   5  0.5   50.0
1          Pop   3  0.3   30.0
2         Jazz   2  0.2   20.0
Total:   Total  10  1.0  100.0

In [12]:
notas= pd.read_excel("exercicio_prova_tabelas.xlsx")
letra = notas["Letras"].value_counts()
totalN = letra.sum()
notasDF = pd.DataFrame(letra.reset_index().values,columns=["Notas","FA"])
notasDF["FR"] = notasDF["FA"]/totalN
notasDF["FR%"] = notasDF["FR"]*100
notasDF.loc["Total: "] = notasDF.sum()
notasDF.loc["Total: ","Notas"]= "Total"
notasDF

         Notas  FA   FR    FR%
0            A   6  0.6   60.0
1            B   3  0.3   30.0
2            C   1  0.1   10.0
Total:   Total  10  1.0  100.0