# Aula 1 - Importanto Pacotes e Tabela de Frequência

Vamos começar importando os pacotes necessários.

In [14]:
import pandas as pd

Importando a base de dados. Lembre que você precisa ter salvo o arquivo na sua pasta de trabalho. Lembre que você precisa indicar para o Python onde fica a sua pasta de trabalho. Faça isso do seguinte modo: File -> Open Folder.

In [15]:
base = pd.read_excel("Resposta_Musical.xlsx")

Verificar as 10 primeiras linhas
base.head(10)

In [16]:
base.head(10)

   ID_Aluno Genero_Musical
0         1            Pop
1         2         Gospel
2         3     Eletrônica
3         4          K-pop
4         5         Reggae
5         6            MPB
6         7            Rap
7         8     Eletrônica
8         9         Pagode
9        10         Gospel

Calcular a frequência absoluta

In [17]:
genero = base["Genero_Musical"].value_counts()

Podemos verificar a estrutura dos dados

In [18]:
genero

Genero_Musical
Eletrônica    12
Reggae        11
Pagode        11
Gospel         9
Rap            8
Sertanejo      8
Jazz           6
Funk           6
Clássica       6
Forró          6
MPB            5
Pop            4
K-pop          4
Rock           3
Hip Hop        1
Name: count, dtype: int64

Colocando o total de participantes

In [19]:
total = genero.sum()
print(total)

100

Quero transformar em um dataframe. Desse modo, podemos trabalhar com mais liberdade com os dados

In [20]:
df = pd.DataFrame(genero)
df

                count
Genero_Musical
Eletrônica         12
Reggae             11
Pagode             11
Gospel              9
Rap                 8
Sertanejo           8
Jazz                6
Funk                6
Clássica            6
Forró               6
MPB                 5
Pop                 4
K-pop               4
Rock                3
Hip Hop             1

Criar uma nova coluna com a frequência relativa. Lembre que a frequência relativa é dada pela seguinte relação $Frequência_Relativa = \frac{Frequência_Relativa}{Total}$

In [21]:
df["Freq_Relativa"] = df["count"]/ total 
df

                count  Freq_Relativa
Genero_Musical
Eletrônica         12           0.12
Reggae             11           0.11
Pagode             11           0.11
Gospel              9           0.09
Rap                 8           0.08
Sertanejo           8           0.08
Jazz                6           0.06
Funk                6           0.06
Clássica            6           0.06
Forró               6           0.06
MPB                 5           0.05
Pop                 4           0.04
K-pop               4           0.04
Rock                3           0.03
Hip Hop             1           0.01

Criar uma coluna com para frequência relativa percentual.

In [22]:
df["Freq_Relativa_%"] = df["Freq_Relativa"]*100
df

                count  Freq_Relativa  Freq_Relativa_%
Genero_Musical
Eletrônica         12           0.12             12.0
Reggae             11           0.11             11.0
Pagode             11           0.11             11.0
Gospel              9           0.09              9.0
Rap                 8           0.08              8.0
Sertanejo           8           0.08              8.0
Jazz                6           0.06              6.0
Funk                6           0.06              6.0
Clássica            6           0.06              6.0
Forró               6           0.06              6.0
MPB                 5           0.05              5.0
Pop                 4           0.04              4.0
K-pop               4           0.04              4.0
Rock                3           0.03              3.0
Hip Hop             1           0.01              1.0

Trocar o nome das colunas.

In [23]:
df.columns = ["Freq_Absoluta","Freq_Relativa","Freq_Relativa_%"]
df

                Freq_Absoluta  Freq_Relativa  Freq_Relativa_%
Genero_Musical
Eletrônica                 12           0.12             12.0
Reggae                     11           0.11             11.0
Pagode                     11           0.11             11.0
Gospel                      9           0.09              9.0
Rap                         8           0.08              8.0
Sertanejo                   8           0.08              8.0
Jazz                        6           0.06              6.0
Funk                        6           0.06              6.0
Clássica                    6           0.06              6.0
Forró                       6           0.06              6.0
MPB                         5           0.05              5.0
Pop                         4           0.04              4.0
K-pop                       4           0.04              4.0
Rock                        3           0.03              3.0
Hip Hop                     1           0.01              1.0

In [24]:
df.loc['Total'] = total
df.loc['Total', 'Freq_Relativa'] = 1.0
df

                Freq_Absoluta  Freq_Relativa  Freq_Relativa_%
Genero_Musical
Eletrônica                 12           0.12             12.0
Reggae                     11           0.11             11.0
Pagode                     11           0.11             11.0
Gospel                      9           0.09              9.0
Rap                         8           0.08              8.0
Sertanejo                   8           0.08              8.0
Jazz                        6           0.06              6.0
Funk                        6           0.06              6.0
Clássica                    6           0.06              6.0
Forró                       6           0.06              6.0
MPB                         5           0.05              5.0
Pop                         4           0.04              4.0
K-pop                       4           0.04              4.0
Rock                        3           0.03              3.0
Hip Hop                     1           0.01              1.0
Total                     100           1.00            100.0

Posso querer saber o valor de algum dado específico.

In [25]:
df.loc["Rap"]

Freq_Absoluta      8.00
Freq_Relativa      0.08
Freq_Relativa_%    8.00
Name: Rap, dtype: float64

Podemos exportar os dados tratados para o excel

In [26]:
df.to_excel("teste2.xlsx")