# Aula 2 Atividade com a Tabela de Frequênca - Revisão

Vou importar os pacotes necessários

In [16]:
import pandas as pd

Vou importar o arquivo de excel que será utilizado

In [17]:
base = pd.read_excel("Atividade_Tabela_Freq.xlsx")
base

    Turma     Gênero  Idade  ALTURA  PESO     REDES  TEMPO
0      1D  Masculino     12     147    62    TikTok      6
1      1D  Masculino     11     151    70    TikTok      1
2      1D  Masculino     12     156    61    TikTok      9
3      1D  Masculino     11     147    71    TikTok     11
4      1D  Masculino     13     155    76    TikTok     12
..    ...        ...    ...     ...   ...       ...    ...
295    1E  Masculino     12     157    79  Whatsapp     67
296    1E  Masculino     12     156    79  Whatsapp     67
297    1E  Masculino     13     155    57  Whatsapp     67
298    1E  Masculino     12     151    75  Whatsapp     67
299    1E  Masculino     12     157    54  Whatsapp     61

[300 rows x 7 columns]

Vou calcular a frequência absoluta.

In [18]:
redes = base["REDES"].value_counts()
redes

REDES
TikTok       164
Whatsapp     102
Instagram     34
Name: count, dtype: int64

Calcular o total

In [19]:
total = redes.sum()
total

300

Transformar em uma base de dados.

In [ ]:
df = pd.DataFrame(redes.reset_index().values, columns=['Rede Social', 'Frequência Absoluta'])
df

  Rede Social Frequência Absoluta
0      TikTok                 164
1    Whatsapp                 102
2   Instagram                  34

Calcular a frequência relativa

In [21]:
df["Frequência Relativa"] = df["Frequência Absoluta"]/total 
df

  Rede Social Frequência Absoluta Frequência Relativa
0      TikTok                 164            0.546667
1    Whatsapp                 102                0.34
2   Instagram                  34            0.113333

In [22]:
df["Frequência Relativa Percentual"] = df["Frequência Relativa"]*100 
df

,Rede Social,Frequência Absoluta,Frequência Relativa,Frequência Relativa Percentual
0,TikTok,164,0.546667,54.666667
1,Whatsapp,102,0.34,34.0
2,Instagram,34,0.113333,11.333333

In [23]:
df.loc["Total"] = df.sum()
df

,Rede Social,Frequência Absoluta,Frequência Relativa,Frequência Relativa Percentual
0,TikTok,164,0.546667,54.666667
1,Whatsapp,102,0.34,34.0
2,Instagram,34,0.113333,11.333333
Total,TikTokWhatsappInstagram,300,1.0,100.0

In [24]:
df.loc["Total","Rede Social"] = "Total"
df

,Rede Social,Frequência Absoluta,Frequência Relativa,Frequência Relativa Percentual
0,TikTok,164,0.546667,54.666667
1,Whatsapp,102,0.34,34.0
2,Instagram,34,0.113333,11.333333
Total,Total,300,1.0,100.0

Agora vou fazer o mesmo procedimento para turmas. Vou fazer de um modo mais fácil nesse caso.

In [25]:
base
turma = base["Turma"].value_counts()
turma

Turma
1E    103
1A    102
1B     33
1D     31
1C     31
Name: count, dtype: int64

In [26]:
turma_df = pd.DataFrame(turma)
turma_df # não resetarei o index nesse caso

       count
Turma
1E       103
1A       102
1B        33
1D        31
1C        31

In [27]:
turma_df["FR"] = turma_df["count"]/total 
turma_df

       count        FR
Turma
1E       103  0.343333
1A       102  0.340000
1B        33  0.110000
1D        31  0.103333
1C        31  0.103333

In [28]:
turma_df["FR%"] = turma_df["FR"]*100
turma_df

       count        FR        FR%
Turma
1E       103  0.343333  34.333333
1A       102  0.340000  34.000000
1B        33  0.110000  11.000000
1D        31  0.103333  10.333333
1C        31  0.103333  10.333333

In [29]:
turma_df.columns = ["FA","FR","FR%"]
turma_df

        FA        FR        FR%
Turma
1E     103  0.343333  34.333333
1A     102  0.340000  34.000000
1B      33  0.110000  11.000000
1D      31  0.103333  10.333333
1C      31  0.103333  10.333333

In [30]:
turma_df.loc["Total"] = turma_df.sum()
turma_df

          FA        FR         FR%
Turma
1E     103.0  0.343333   34.333333
1A     102.0  0.340000   34.000000
1B      33.0  0.110000   11.000000
1D      31.0  0.103333   10.333333
1C      31.0  0.103333   10.333333
Total  300.0  1.000000  100.000000